name: F# CI

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

permissions:
 contents: read

jobs:
 build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Ajuste para a versão do .NET SDK que você deseja usar
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: */obj
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.fsproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
